import { z } from 'zod';

export const TRACE_SCHEMA_VERSION = 1;

const gameStateSchema = z.enum(['NOT_PLAYED', 'NOT_FINISHED', 'WIN', 'GAME_OVER']);
const gameTypeSchema = z.enum(['arc2', 'arc3']);

export const stepRecordSchema = z.object({
  runId: z.string(),
  model: z.string(),
  gameId: z.string(),
  gameType: gameTypeSchema,
  runNumber: z.number().int().nonnegative(),
  step: z.number().int().nonnegative(),
  action: z.string(),
  score: z.number().min(0).max(1),
  level: z.number().int().nullable(),
  totalLevels: z.number().int().nullable(),
  done: z.boolean(),
  state: gameStateSchema,
  cumulativeCostUsd: z.number().nonnegative(),
  inputTokens: z.number().int().nonnegative(),
  outputTokens: z.number().int().nonnegative(),
  notepadLength: z.number().int().nonnegative(),
  reasoning: z.string(),
  notepadContents: z.string(),
  observation: z.string(),
  scorePct: z.number().min(0).max(100),
  stepCostUsd: z.number().nonnegative(),
  reasoningTokens: z.number().int().nonnegative(),
  thinkingText: z.string().nullable(),
  cachedInputTokens: z.number().int().nonnegative(),
  cacheWriteTokens: z.number().int().nonnegative(),
  promptMessages: z.array(z.object({
    role: z.enum(['user', 'assistant', 'system']),
    content: z.string(),
  })).optional(),
});

export const runRecordSchema = z.object({
  runId: z.string(),
  model: z.string(),
  gameId: z.string(),
  gameType: gameTypeSchema,
  runNumber: z.number().int().nonnegative(),
  totalSteps: z.number().int().nonnegative(),
  maxSteps: z.number().int().positive(),
  finalScore: z.number().min(0).max(1),
  solved: z.boolean(),
  levelsCompleted: z.number().int().nullable(),
  totalLevels: z.number().int().nullable(),
  costUsd: z.number().nonnegative(),
  totalInputTokens: z.number().int().nonnegative(),
  totalOutputTokens: z.number().int().nonnegative(),
  totalReasoningTokens: z.number().int().nonnegative(),
  elapsedSeconds: z.number().nonnegative(),
  notepadFinal: z.string(),
  error: z.string().nullable(),
  modelId: z.string(),
  seed: z.number().int().catch(0),
  finalScorePct: z.number().min(0).max(100),
  totalCachedInputTokens: z.number().int().nonnegative(),
  totalCacheWriteTokens: z.number().int().nonnegative(),
  resetCount: z.number().int().nonnegative(),
  resetAttempts: z.number().int().nonnegative(),
  resetSuccesses: z.number().int().nonnegative(),
});

export const traceHeaderSchema = z.object({
  type: z.literal('header'),
  schemaVersion: z.number().int().positive(),
  runId: z.string(),
  model: z.string(),
  gameId: z.string(),
  gameType: gameTypeSchema,
  runNumber: z.number().int().nonnegative(),
  seed: z.number().int().catch(0),
  maxSteps: z.number().int().positive(),
  systemPrompt: z.string(),
  timestamp: z.string(),
});

export const traceStepSchema = z.object({
  type: z.literal('step'),
  step: z.number().int().nonnegative(),
  action: z.string(),
  score: z.number(),
  scorePct: z.number(),
  level: z.number().int().nullable(),
  totalLevels: z.number().int().nullable(),
  done: z.boolean(),
  state: gameStateSchema,
  reasoning: z.string(),
  observation: z.string(),
  notepadContents: z.string(),
  inputTokens: z.number().int().nonnegative(),
  outputTokens: z.number().int().nonnegative(),
  reasoningTokens: z.number().int().nonnegative(),
  thinkingText: z.string().nullable(),
  cachedInputTokens: z.number().int().nonnegative(),
  cacheWriteTokens: z.number().int().nonnegative(),
  stepCostUsd: z.number().nonnegative(),
  cumulativeCostUsd: z.number().nonnegative(),
  imageSent: z.boolean(),
  rawResponseFile: z.string().nullable(),
  promptMessages: z.array(z.object({
    role: z.enum(['user', 'assistant', 'system']),
    content: z.string(),
  })).optional(),
  timestamp: z.string(),
});

export const traceSummarySchema = z.object({
  type: z.literal('summary'),
  runId: z.string(),
  model: z.string(),
  gameId: z.string(),
  gameType: gameTypeSchema,
  runNumber: z.number().int().nonnegative(),
  totalSteps: z.number().int().nonnegative(),
  finalScore: z.number(),
  finalScorePct: z.number(),
  solved: z.boolean(),
  costUsd: z.number().nonnegative(),
  totalInputTokens: z.number().int().nonnegative(),
  totalOutputTokens: z.number().int().nonnegative(),
  totalReasoningTokens: z.number().int().nonnegative(),
  elapsedSeconds: z.number().nonnegative(),
  error: z.string().nullable(),
  timestamp: z.string(),
});

export const traceRecordSchema = z.discriminatedUnion('type', [
  traceHeaderSchema,
  traceStepSchema,
  traceSummarySchema,
]);
