/**
 * Author: Cascade
 * Date: 2026-01-05T17:25:00Z
 * PURPOSE: Contracts + DTOs for explanation persistence layer, kept in sync with ExplanationRepository mappings.
 * SRP/DRY check: Pass — reviewed repository mapRowToExplanation output for parity.
 */

/**
 * Explanation Repository Interface
 *
 * Defines the contract for explanation data access operations.
 * Separates explanation-related database operations from other concerns.
 */

export interface ExplanationData {
  id?: number; // Optional - auto-generated by database, but needed for debate mode context
  puzzleId: string;
  patternDescription: string;
  solvingStrategy: string;
  hints: string[];
  confidence: number;
  alienMeaningConfidence?: number | null;
  alienMeaning?: string | null;
  modelName: string;
  reasoningLog?: string | null;
  hasReasoningLog?: boolean;
  providerResponseId?: string | null;
  apiProcessingTimeMs?: number | null;
  saturnImages?: any | null;
  saturnLog?: any | null;
  saturnEvents?: any | null;
  saturnSuccess?: boolean | null;
  predictedOutputGrid?: any | null;
  isPredictionCorrect?: boolean | null;
  trustworthinessScore?: number | null;
  providerRawResponse?: any | null;
  reasoningItems?: any | null;
  temperature?: number | null;
  reasoningEffort?: string | null;
  reasoningVerbosity?: string | null;
  reasoningSummaryType?: string | null;
  inputTokens?: number | null;
  outputTokens?: number | null;
  reasoningTokens?: number | null;
  totalTokens?: number | null;
  estimatedCost?: number | null;
  multiplePredictedOutputs?: any | null;
  multiTestResults?: any | null;
  multiTestAllCorrect?: boolean | null;
  multiTestAverageAccuracy?: number | null;
  hasMultiplePredictions?: boolean | null;
  multiTestPredictionGrids?: any | null;
  // BeeTree ensemble metadata fields (optional)
  beetreeStage?: string | null;
  beetreeConsensusCount?: number | null;
  beetreeModelResults?: any | null;
  beetreeCostBreakdown?: any | null;
  beetreeTokenUsage?: any | null;
  beetreeRunTimestamp?: string | null;
  beetreeMode?: string | null;
  beetreeConsensusStrength?: number | null;
  beetreeDiversityScore?: number | null;
  // NEW: Prompt tracking fields for full traceability
  systemPromptUsed?: string | null;
  userPromptUsed?: string | null;
  promptTemplateId?: string | null;
  customPromptText?: string | null;
  rebuttingExplanationId?: number | null;
  // NEW: Grover iterative solver fields
  groverIterations?: any | null;
  groverBestProgram?: string | null;
  iterationCount?: number | null;
  // NEW: LLM Council multi-model consensus fields
  councilMode?: 'solve' | 'assess' | null;
  councilStage1Results?: any | null;
  councilStage2Rankings?: any | null;
  councilStage3Synthesis?: any | null;
  councilMetadata?: any | null;
  councilAssessedExplanationIds?: number[] | null;
  councilAggregateRankings?: any | null;
  councilPromptUsed?: string | null;
  createdAt?: string; // Also optional - auto-generated but useful for debate context
  // Note: id and created_at are auto-generated by database
}

export interface ExplanationResponse {
  id: number;
  puzzleId: string;
  patternDescription: string;
  solvingStrategy: string;
  hints: string[];
  confidence: number;
  alienMeaningConfidence: number | null;
  alienMeaning: string | null;
  modelName: string;
  reasoningLog: string | null;
  hasReasoningLog: boolean;
  providerResponseId: string | null;
  apiProcessingTimeMs: number | null;
  saturnImages: any | null;
  saturnLog: any | null;
  saturnEvents: any | null;
  saturnSuccess: boolean | null;
  predictedOutputGrid: number[][] | null;
  isPredictionCorrect: boolean | null;
  trustworthinessScore: number | null;
  providerRawResponse: any | null;
  reasoningItems: any | null;
  temperature: number | null;
  reasoningEffort: string | null;
  reasoningVerbosity: string | null;
  reasoningSummaryType: string | null;
  inputTokens: number | null;
  outputTokens: number | null;
  reasoningTokens: number | null;
  totalTokens: number | null;
  estimatedCost: number | null;
  multiplePredictedOutputs: any | null;
  multiTestResults: any | null;
  multiTestAllCorrect: boolean | null;
  multiTestAverageAccuracy?: number | null;
  hasMultiplePredictions?: boolean | null;
  multiTestPredictionGrids?: any | null;
  // NEW: Prompt tracking fields for full traceability
  systemPromptUsed: string | null;
  userPromptUsed: string | null;
  promptTemplateId: string | null;
  customPromptText: string | null;
  rebuttingExplanationId: number | null;
  // NEW: Grover iterative solver fields
  groverIterations: any | null;
  groverBestProgram: string | null;
  iterationCount: number | null;
  // NEW: LLM Council multi-model consensus fields
  councilMode: 'solve' | 'assess' | null;
  councilStage1Results: any | null;
  councilStage2Rankings: any | null;
  councilStage3Synthesis: any | null;
  councilMetadata: any | null;
  councilAssessedExplanationIds: number[] | null;
  councilAggregateRankings: any | null;
  councilPromptUsed: string | null;
  // Beetree multi-model fields
  beetreeModelResults?: any | null;
  beetreeCostBreakdown?: any | null;
  beetreeTokenUsage?: any | null;
  createdAt: string;
  helpfulVotes?: number;
  notHelpfulVotes?: number;
}

export interface ExplanationSummaryPage {
  items: ExplanationResponse[];
  total: number;
  filteredTotal: number;
  counts: {
    all: number;
    correct: number;
    incorrect: number;
  };
}

export interface BulkExplanationStatus {
  [puzzleId: string]: {
    hasExplanation: boolean;
    explanationId: number | null;
    feedbackCount: number;
    apiProcessingTimeMs: number | null;
    modelName: string | null;
    createdAt: Date | null;
    confidence: number | null;
    estimatedCost: number | null;
    alienMeaningConfidence: number | null;
    alienMeaning: string | null;
    reasoningLog: string | null;
    hasReasoningLog: boolean | null;
    providerResponseId: string | null;
    saturnImages: any | null;
    saturnLog: any | null;
    saturnEvents: any | null;
    saturnSuccess: boolean | null;
    predictedOutputGrid: any | null;
    isPredictionCorrect: boolean | null;
    trustworthinessScore: number | null;
    providerRawResponse: any | null;
    reasoningItems: any | null;
    temperature: number | null;
    reasoningEffort: string | null;
    reasoningVerbosity: string | null;
    reasoningSummaryType: string | null;
    inputTokens: number | null;
    outputTokens: number | null;
    reasoningTokens: number | null;
    totalTokens: number | null;
    multiplePredictedOutputs: any | null;
    multiTestResults: any | null;
    multiTestAllCorrect: boolean | null;
    multiTestAverageAccuracy: number | null;
    hasMultiplePredictions: boolean | null;
    multiTestPredictionGrids: any | null;
    isSolved?: boolean; // Whether any model has produced a correct prediction for this puzzle
  };
}

/**
 * Lightweight bulk explanation status - returns only fields used by puzzle list views
 * Reduces data transfer by 99% compared to full BulkExplanationStatus
 *
 * Includes apiProcessingTimeMs because:
 * - puzzleService.getPuzzleList() and puzzleOverviewService.buildPuzzleMap() both read it
 * - Single numeric field has negligible impact on payload size
 * - Omitted fields are large JSONB blobs (saturnImages, providerRawResponse, etc.)
 */
export interface BulkExplanationStatusLight {
  [puzzleId: string]: {
    hasExplanation: boolean;
    explanationId: number | null;
    modelName: string | null;
    createdAt: Date | null;
    confidence: number | null;
    estimatedCost: number | null;
    apiProcessingTimeMs: number | null;
    feedbackCount: number;
    isSolved: boolean;
  };
}

/**
 * Interface for Explanation Repository
 */
export interface IExplanationRepository {
  /**
   * Save a new explanation for a puzzle
   */
  saveExplanation(data: ExplanationData): Promise<ExplanationResponse>;

  /**
   * Get the most recent explanation for a puzzle
   */
  getExplanationForPuzzle(puzzleId: string): Promise<ExplanationResponse | null>;

  /**
   * Get all explanations for a puzzle (multiple models/attempts)
   * @param puzzleId - The puzzle ID to get explanations for
   * @param correctnessFilter - Optional filter: 'all', 'correct', or 'incorrect'
   */
  getExplanationsForPuzzle(puzzleId: string, correctnessFilter?: 'all' | 'correct' | 'incorrect'): Promise<ExplanationResponse[]>;

  /**
   * Get paginated explanation summaries for a puzzle.
   * Returns lightweight rows (no grid JSON) with aggregate counts for filters.
   */
  getExplanationSummariesForPuzzle(
    puzzleId: string,
    options?: {
      correctnessFilter?: 'all' | 'correct' | 'incorrect';
      limit?: number;
      offset?: number;
    }
  ): Promise<ExplanationSummaryPage>;

  /**
   * Get explanation by ID
   */
  getExplanationById(id: number): Promise<ExplanationResponse | null>;

  /**
   * Check if puzzle has any explanations
   */
  hasExplanation(puzzleId: string): Promise<boolean>;

  /**
   * Get bulk explanation status for multiple puzzles
   */
  getBulkExplanationStatus(puzzleIds: string[]): Promise<BulkExplanationStatus>;

  /**
   * Get lightweight bulk explanation status for multiple puzzles
   * Returns only fields actually used by puzzle list views (8 fields vs 37)
   * Dramatically reduces temp file usage and improves query performance
   */
  getBulkExplanationStatusLight(puzzleIds: string[]): Promise<BulkExplanationStatusLight>;
}
